### ISSUE TITLE
Tab's comment

### ISSUE THREAD

**Issue by tobireif** [WICG/container-queries#9]
Not an issue, just something relevant:

https://www.xanthir.com/b4PR0#4PR0-27

**Comment by ZeeCoder** [comment]
I think Chrome's 64 version is published either this or next month, with a native ResizeObserver.
And yes, it is a game changer in terms of efficiency.

I've made a demo to demonstrate the difference:
https://codesandbox.io/s/l3rmm1rz2l

If you open it with v64, all the changes are instant.

**Comment by beep** [comment]
I don’t think there’s anything actionable on this issue, so I’m closing this out for now.

(@tobireif, if there’s somewhere in the cq-usecases repo where you’d like this captured, please add it! Feel free to toss it into our wiki, or to open a PR if you think it should be part of [our first milestone](https://github.com/WICG/cq-usecases/milestone/1). Thanks!)
